class My_exception(Exception):
  pass
